version: "3.9"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - migration
    ports:
      - "8000:8000"
  migration:
    build: .
    command: bash -c "python manage.py migrate --noinput && echo "from init_db import main; main(); exit()" | python3 manage.py shell"
    volumes:
      - .:/code