# Generated by Django 3.2.9 on 2021-12-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name Of Shipment')),
                ('description', models.CharField(max_length=100, verbose_name='Description Of Shipment')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Amount')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Price of Shipment')),
            ],
        ),
    ]
